# COVID 19 DATA ANALYSIS

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("country_wise_latest.csv")

In [3]:
df.columns

Index(['Country/Region', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'New cases', 'New deaths', 'New recovered', 'Deaths / 100 Cases',
       'Recovered / 100 Cases', 'Deaths / 100 Recovered',
       'Confirmed last week', '1 week change', '1 week % increase',
       'WHO Region'],
      dtype='str')

In [4]:
df.head(2)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe

In [5]:
#total confirmed cases
print(f"Total Confirmed Cases : {df["Confirmed"].sum()}")

Total Confirmed Cases : 16480485

In [6]:
#total deaths 
print(f"Total Deaths : {df["Deaths"].sum()}")

Total Deaths : 654036

In [7]:
#total recovered
print(f"Total Recovered : {df["Recovered"].sum()}")

Total Recovered : 9468087

In [8]:
#total active cases
print(f"Total Active Cases : {df["Active"].sum()}")

Total Active Cases : 6358362

In [9]:
# total countries
print(f"Total Countries : {df["Country/Region"].nunique()}")

Total Countries : 187

In [10]:
# top 10 countries by confirmed cases
df.sort_values("Confirmed", ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
35,Chile,347923,9187,319954,18782,2133,75,1859,2.64,91.96,2.87,333029,14894,4.47,Americas
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe
81,Iran,293606,15912,255144,22550,2434,212,1931,5.42,86.90,6.24,276202,17404,6.30,Eastern Mediterranean

In [11]:
# top 10 countries by death
df.sort_values("Deaths",ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
85,Italy,246286,35112,198593,12581,168,5,147,14.26,80.64,17.68,244624,1662,0.68,Europe
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
61,France,220352,30212,81212,108928,2551,17,267,13.71,36.86,37.20,214023,6329,2.96,Europe
157,Spain,272421,28432,150376,93613,0,0,0,10.44,55.20,18.91,264836,7585,2.86,Europe
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
81,Iran,293606,15912,255144,22550,2434,212,1931,5.42,86.90,6.24,276202,17404,6.30,Eastern Mediterranean

In [12]:
#top 10 countries by recovered cases
df.sort_values("Recovered",ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
35,Chile,347923,9187,319954,18782,2133,75,1859,2.64,91.96,2.87,333029,14894,4.47,Americas
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
81,Iran,293606,15912,255144,22550,2434,212,1931,5.42,86.90,6.24,276202,17404,6.30,Eastern Mediterranean
128,Pakistan,274289,5842,241026,27421,1176,20,3592,2.13,87.87,2.42,266096,8193,3.08,Eastern Mediterranean

In [13]:
#top 10 countries by active cases
df.sort_values("Active",ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
37,Colombia,257101,8777,131161,117163,16306,508,11494,3.41,51.02,6.69,204005,53096,26.03,Americas
61,France,220352,30212,81212,108928,2551,17,267,13.71,36.86,37.20,214023,6329,2.96,Europe
32,Canada,116458,8944,0,107514,682,11,0,7.68,0.00,inf,112925,3533,3.13,Americas
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas

In [14]:
#bottom 10 countries by confirmed cases
df.sort_values("Confirmed").head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
183,Western Sahara,10,1,8,1,0,0,0,10.0,80.00,12.5,10,0,0.00,Africa
75,Holy See,12,0,12,0,0,0,0,0.0,100.00,0.0,12,0,0.00,Europe
68,Greenland,14,0,13,1,1,0,0,0.0,92.86,0.0,13,1,7.69,Europe
140,Saint Kitts and Nevis,17,0,15,2,0,0,0,0.0,88.24,0.0,17,0,0.00,Americas
49,Dominica,18,0,18,0,0,0,0,0.0,100.00,0.0,18,0,0.00,Americas
94,Laos,20,0,19,1,0,0,0,0.0,95.00,0.0,19,1,5.26,Western Pacific
69,Grenada,23,0,23,0,0,0,0,0.0,100.00,0.0,23,0,0.00,Americas
168,Timor-Leste,24,0,0,24,0,0,0,0.0,0.00,0.0,24,0,0.00,South-East Asia
141,Saint Lucia,24,0,22,2,0,0,0,0.0,91.67,0.0,23,1,4.35,Americas
59,Fiji,27,0,18,9,0,0,0,0.0,66.67,0.0,27,0,0.00,Western Pacific

In [15]:
#bottom 10 countries by deaths
df.sort_values("Deaths").head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
30,Cambodia,226,0,147,79,1,0,4,0.0,65.04,0.0,171,55,32.16,Western Pacific
19,Bhutan,99,0,86,13,4,0,1,0.0,86.87,0.0,90,9,10.00,South-East Asia
59,Fiji,27,0,18,9,0,0,0,0.0,66.67,0.0,27,0,0.00,Western Pacific
55,Eritrea,265,0,191,74,2,0,2,0.0,72.08,0.0,251,14,5.58,Africa
49,Dominica,18,0,18,0,0,0,0,0.0,100.00,0.0,18,0,0.00,Americas
75,Holy See,12,0,12,0,0,0,0,0.0,100.00,0.0,12,0,0.00,Europe
68,Greenland,14,0,13,1,1,0,0,0.0,92.86,0.0,13,1,7.69,Europe
69,Grenada,23,0,23,0,0,0,0,0.0,100.00,0.0,23,0,0.00,Americas
94,Laos,20,0,19,1,0,0,0,0.0,95.00,0.0,19,1,5.26,Western Pacific
114,Mongolia,289,0,222,67,1,0,4,0.0,76.82,0.0,287,2,0.70,Western Pacific

In [16]:
#country with highest confirmed cases
df.loc[df["Confirmed"].idxmax()]

Country/Region                  US
Confirmed                  4290259
Deaths                      148011
Recovered                  1325804
Active                     2816444
New cases                    56336
New deaths                    1076
New recovered                27941
Deaths / 100 Cases            3.45
Recovered / 100 Cases         30.9
Deaths / 100 Recovered       11.16
Confirmed last week        3834677
1 week change               455582
1 week % increase            11.88
WHO Region                Americas
Name: 173, dtype: object

In [17]:
#country with highest deaths
df.loc[df["Deaths"].idxmax()]

Country/Region                  US
Confirmed                  4290259
Deaths                      148011
Recovered                  1325804
Active                     2816444
New cases                    56336
New deaths                    1076
New recovered                27941
Deaths / 100 Cases            3.45
Recovered / 100 Cases         30.9
Deaths / 100 Recovered       11.16
Confirmed last week        3834677
1 week change               455582
1 week % increase            11.88
WHO Region                Americas
Name: 173, dtype: object

In [18]:
#country with highest recovered
df.loc[df["Recovered"].idxmax()]

Country/Region              Brazil
Confirmed                  2442375
Deaths                       87618
Recovered                  1846641
Active                      508116
New cases                    23284
New deaths                     614
New recovered                33728
Deaths / 100 Cases            3.59
Recovered / 100 Cases        75.61
Deaths / 100 Recovered        4.74
Confirmed last week        2118646
1 week change               323729
1 week % increase            15.28
WHO Region                Americas
Name: 23, dtype: object

In [19]:
#country with highest active cases
df.loc[df["Active"].idxmax()]

Country/Region                  US
Confirmed                  4290259
Deaths                      148011
Recovered                  1325804
Active                     2816444
New cases                    56336
New deaths                    1076
New recovered                27941
Deaths / 100 Cases            3.45
Recovered / 100 Cases         30.9
Deaths / 100 Recovered       11.16
Confirmed last week        3834677
1 week change               455582
1 week % increase            11.88
WHO Region                Americas
Name: 173, dtype: object

In [20]:
#confirmed cases by WHO region
df.groupby("WHO Region")["Confirmed"].sum()

WHO Region
Africa                    723207
Americas                 8839286
Eastern Mediterranean    1490744
Europe                   3299523
South-East Asia          1835297
Western Pacific           292428
Name: Confirmed, dtype: int64

In [21]:
#deaths by WHO region
df.groupby("WHO Region")["Deaths"].sum()

WHO Region
Africa                    12223
Americas                 342732
Eastern Mediterranean     38339
Europe                   211144
South-East Asia           41349
Western Pacific            8249
Name: Deaths, dtype: int64

In [22]:
#recovered cases by WHO region
df.groupby("WHO Region")["Recovered"].sum()

WHO Region
Africa                    440645
Americas                 4468616
Eastern Mediterranean    1201400
Europe                   1993723
South-East Asia          1156933
Western Pacific           206770
Name: Recovered, dtype: int64

In [23]:
#active cases by WHO region
df.groupby("WHO Region")["Active"].sum()

WHO Region
Africa                    270339
Americas                 4027938
Eastern Mediterranean     251005
Europe                   1094656
South-East Asia           637015
Western Pacific            77409
Name: Active, dtype: int64

In [24]:
#avg confirmed cases by WHO region
df.groupby("WHO Region")["Confirmed"].mean()

WHO Region
Africa                    15066.812500
Americas                 252551.028571
Eastern Mediterranean     67761.090909
Europe                    58920.053571
South-East Asia          183529.700000
Western Pacific           18276.750000
Name: Confirmed, dtype: float64

In [25]:
#top 10 countries by new cases
df.sort_values("New cases", ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
37,Colombia,257101,8777,131161,117163,16306,508,11494,3.41,51.02,6.69,204005,53096,26.03,Americas
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
13,Bangladesh,226225,2965,125683,97577,2772,37,1801,1.31,55.56,2.36,207453,18772,9.05,South-East Asia

In [26]:
# top 10 countries by new deaths 
df.sort_values("New deaths",ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
37,Colombia,257101,8777,131161,117163,16306,508,11494,3.41,51.02,6.69,204005,53096,26.03,Americas
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
81,Iran,293606,15912,255144,22550,2434,212,1931,5.42,86.90,6.24,276202,17404,6.30,Eastern Mediterranean
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
82,Iraq,112585,4458,77144,30983,2553,96,1927,3.96,68.52,5.78,94693,17892,18.89,Eastern Mediterranean

In [27]:
#top 10 countries by new recovered
df.sort_values("New recovered",ascending=False).head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
23,Brazil,2442375,87618,1846641,508116,23284,614,33728,3.59,75.61,4.74,2118646,323729,15.28,Americas
79,India,1480073,33408,951166,495499,44457,637,33598,2.26,64.26,3.51,1155338,324735,28.11,South-East Asia
173,US,4290259,148011,1325804,2816444,56336,1076,27941,3.45,30.90,11.16,3834677,455582,11.88,Americas
37,Colombia,257101,8777,131161,117163,16306,508,11494,3.41,51.02,6.69,204005,53096,26.03,Americas
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
111,Mexico,395489,44022,303810,47657,4973,342,8588,11.13,76.82,14.49,349396,46093,13.19,Americas
132,Peru,389717,18418,272547,98752,13756,575,4697,4.73,69.93,6.76,357681,32036,8.96,Americas
128,Pakistan,274289,5842,241026,27421,1176,20,3592,2.13,87.87,2.42,266096,8193,3.08,Eastern Mediterranean
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
145,Saudi Arabia,268934,2760,222936,43238,1993,27,2613,1.03,82.90,1.24,253349,15585,6.15,Eastern Mediterranean

In [28]:
#recovery rate 
df["Recovery Rate"] = (df["Recovered"]/df["Confirmed"])*100
df.sort_values("Recovery Rate",ascending=False)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region,Recovery Rate
49,Dominica,18,0,18,0,0,0,0,0.00,100.00,0.00,18,0,0.00,Americas,100.000000
75,Holy See,12,0,12,0,0,0,0,0.00,100.00,0.00,12,0,0.00,Europe,100.000000
69,Grenada,23,0,23,0,0,0,0,0.00,100.00,0.00,23,0,0.00,Americas,100.000000
48,Djibouti,5059,58,4977,24,9,0,11,1.15,98.38,1.17,5020,39,0.78,Eastern Mediterranean,98.379126
78,Iceland,1854,10,1823,21,7,0,0,0.54,98.33,0.55,1839,15,0.82,Europe,98.327940
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,Mozambique,1701,11,0,1690,32,0,0,0.65,0.00,inf,1507,194,12.87,Africa,0.000000
147,Serbia,24141,543,0,23598,411,9,0,2.25,0.00,inf,21253,2888,13.59,Europe,0.000000
168,Timor-Leste,24,0,0,24,0,0,0,0.00,0.00,0.00,24,0,0.00,South-East Asia,0.000000
161,Sweden,79395,5700,0,73695,398,3,0,7.18,0.00,inf,78048,1347,1.73,Europe,0.000000
163,Syria,674,40,0,634,24,2,0,5.93,0.00,inf,522,152,29.12,Eastern Mediterranean,0.000000

In [29]:
#death rate 
df["Death Rate"] = (df["Deaths"]/df["Confirmed"])*100
df.sort_values("Death Rate",ascending=False)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region,Recovery Rate,Death Rate
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean,49.260792,28.562980
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe,0.476288,15.194824
16,Belgium,66428,9822,17452,39154,402,1,14,14.79,26.27,56.28,64094,2334,3.64,Europe,26.272054,14.785934
85,Italy,246286,35112,198593,12581,168,5,147,14.26,80.64,17.68,244624,1662,0.68,Europe,80.635115,14.256596
61,France,220352,30212,81212,108928,2551,17,267,13.71,36.86,37.20,214023,6329,2.96,Europe,36.855577,13.710790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Saint Lucia,24,0,22,2,0,0,0,0.00,91.67,0.00,23,1,4.35,Americas,91.666667,0.000000
130,Papua New Guinea,62,0,11,51,0,0,0,0.00,17.74,0.00,19,43,226.32,Western Pacific,17.741935,0.000000
142,Saint Vincent and the Grenadines,52,0,39,13,0,0,0,0.00,75.00,0.00,50,2,4.00,Americas,75.000000,0.000000
168,Timor-Leste,24,0,0,24,0,0,0,0.00,0.00,0.00,24,0,0.00,South-East Asia,0.000000,0.000000
181,Vietnam,431,0,365,66,11,0,0,0.00,84.69,0.00,384,47,12.24,Western Pacific,84.686775,0.000000

In [30]:
#active case rate
df["Active Case Rate"] = (df["Active"]/df["Confirmed"])*100
df.sort_values("Active Case Rate",ascending=False)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region,Recovery Rate,Death Rate,Active Case Rate
168,Timor-Leste,24,0,0,24,0,0,0,0.00,0.00,0.00,24,0,0.00,South-East Asia,0.000000,0.000000,100.000000
117,Mozambique,1701,11,0,1690,32,0,0,0.65,0.00,inf,1507,194,12.87,Africa,0.000000,0.646678,99.353322
147,Serbia,24141,543,0,23598,411,9,0,2.25,0.00,inf,21253,2888,13.59,Europe,0.000000,2.249285,97.750715
118,Namibia,1843,8,101,1734,68,0,26,0.43,5.48,7.92,1344,499,37.13,Africa,5.480195,0.434075,94.085730
163,Syria,674,40,0,634,24,2,0,5.93,0.00,inf,522,152,29.12,Eastern Mediterranean,0.000000,5.934718,94.065282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,Brunei,141,3,138,0,0,0,0,2.13,97.87,2.17,141,0,0.00,Western Pacific,97.872340,2.127660,0.000000
49,Dominica,18,0,18,0,0,0,0,0.00,100.00,0.00,18,0,0.00,Americas,100.000000,0.000000,0.000000
75,Holy See,12,0,12,0,0,0,0,0.00,100.00,0.00,12,0,0.00,Europe,100.000000,0.000000,0.000000
69,Grenada,23,0,23,0,0,0,0,0.00,100.00,0.00,23,0,0.00,Americas,100.000000,0.000000,0.000000
143,San Marino,699,42,657,0,0,0,0,6.01,93.99,6.39,699,0,0.00,Europe,93.991416,6.008584,0.000000

In [31]:
#mean confirmed cases
print(f"Confirmed Cases Mean : {df["Confirmed"].mean()}")

Confirmed Cases Mean : 88130.935828877

In [32]:
#median confirmed cases
df["Confirmed"].median()

np.float64(5059.0)

In [33]:
#standard deviation of confirmed cases
df["Confirmed"].std()

np.float64(383318.6638306154)

In [36]:
print(df.isnull().sum())

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
Recovery Rate             0
Death Rate                0
Active Case Rate          0
dtype: int64

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df.dtypes

Country/Region                str
Confirmed                   int64
Deaths                      int64
Recovered                   int64
Active                      int64
New cases                   int64
New deaths                  int64
New recovered               int64
Deaths / 100 Cases        float64
Recovered / 100 Cases     float64
Deaths / 100 Recovered    float64
Confirmed last week         int64
1 week change               int64
1 week % increase         float64
WHO Region                    str
Recovery Rate             float64
Death Rate                float64
Active Case Rate          float64
dtype: object

In [39]:
df["WHO Region"].nunique()

6

In [40]:
df["Country/Region"].nunique()

187

In [42]:
#country wise recovery percenatge
df[df["Recovery Rate"] > 90 ]

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region,Recovery Rate,Death Rate,Active Case Rate
12,Bahrain,39482,141,36110,3231,351,1,421,0.36,91.46,0.39,36936,2546,6.89,Eastern Mediterranean,91.459399,0.357125,8.183476
24,Brunei,141,3,138,0,0,0,0,2.13,97.87,2.17,141,0,0.00,Western Pacific,97.872340,2.127660,0.000000
35,Chile,347923,9187,319954,18782,2133,75,1859,2.64,91.96,2.87,333029,14894,4.47,Americas,91.961152,2.640527,5.398321
36,China,86783,4656,78869,3258,213,4,7,5.37,90.88,5.90,85622,1161,1.36,Western Pacific,90.880702,5.365106,3.754191
38,Comoros,354,7,328,19,0,0,0,1.98,92.66,2.13,334,20,5.99,Africa,92.655367,1.977401,5.367232
44,Cuba,2532,87,2351,94,37,0,2,3.44,92.85,3.70,2446,86,3.52,Americas,92.851501,3.436019,3.712480
47,Denmark,13761,613,12605,543,109,0,77,4.45,91.60,4.86,13453,308,2.29,Europe,91.599448,4.454618,3.945934
48,Djibouti,5059,58,4977,24,9,0,11,1.15,98.38,1.17,5020,39,0.78,Eastern Mediterranean,98.379126,1.146472,0.474402
49,Dominica,18,0,18,0,0,0,0,0.00,100.00,0.00,18,0,0.00,Americas,100.000000,0.000000,0.000000
56,Estonia,2034,69,1923,42,0,0,1,3.39,94.54,3.59,2021,13,0.64,Europe,94.542773,3.392330,2.064897
60,Finland,7398,329,6920,149,5,0,0,4.45,93.54,4.75,7340,58,0.79,Europe,93.538794,4.447148,2.014058
65,Germany,207112,9125,190314,7673,445,1,259,4.41,91.89,4.79,203325,3787,1.86,Europe,91.889412,4.405829,3.704759
68,Greenland,14,0,13,1,1,0,0,0.00,92.86,0.00,13,1,7.69,Europe,92.857143,0.000000,7.142857
69,Grenada,23,0,23,0,0,0,0,0.00,100.00,0.00,23,0,0.00,Americas,100.000000,0.000000,0.000000
75,Holy See,12,0,12,0,0,0,0,0.00,100.00,0.00,12,0,0.00,Europe,100.000000,0.000000,0.000000
78,Iceland,1854,10,1823,21,7,0,0,0.54,98.33,0.55,1839,15,0.82,Europe,98.327940,0.539374,1.132686
83,Ireland,25892,1764,23364,764,11,0,0,6.81,90.24,7.55,25766,126,0.49,Europe,90.236366,6.812915,2.950718
94,Laos,20,0,19,1,0,0,0,0.00,95.00,0.00,19,1,5.26,Western Pacific,95.000000,0.000000,5.000000
100,Liechtenstein,86,1,81,4,0,0,0,1.16,94.19,1.23,86,0,0.00,Europe,94.186047,1.162791,4.651163
105,Malaysia,8904,124,8601,179,7,0,1,1.39,96.60,1.44,8800,104,1.18,Western Pacific,96.597035,1.392633,2.010332
108,Malta,701,9,665,27,1,0,0,1.28,94.86,1.35,677,24,3.55,Europe,94.864479,1.283880,3.851641
110,Mauritius,344,10,332,2,0,0,0,2.91,96.51,3.01,343,1,0.29,Africa,96.511628,2.906977,0.581395
121,New Zealand,1557,22,1514,21,1,0,1,1.41,97.24,1.45,1555,2,0.13,Western Pacific,97.238279,1.412974,1.348748
123,Niger,1132,69,1027,36,0,0,0,6.10,90.72,6.72,1105,27,2.44,Africa,90.724382,6.095406,3.180212
126,Norway,9132,255,8752,125,15,0,0,2.79,95.84,2.91,9034,98,1.08,Europe,95.838809,2.792378,1.368813
136,Qatar,109597,165,106328,3104,292,0,304,0.15,97.02,0.16,107037,2560,2.39,Eastern Mediterranean,97.017254,0.150552,2.832194
141,Saint Lucia,24,0,22,2,0,0,0,0.00,91.67,0.00,23,1,4.35,Americas,91.666667,0.000000,8.333333
143,San Marino,699,42,657,0,0,0,0,6.01,93.99,6.39,699,0,0.00,Europe,93.991416,6.008584,0.000000
155,South Korea,14203,300,13007,896,28,1,102,2.11,91.58,2.31,13816,387,2.80,Western Pacific,91.579244,2.112230,6.308526
164,Taiwan*,462,7,440,15,4,0,0,1.52,95.24,1.59,451,11,2.44,Western Pacific,95.238095,1.515152,3.246753
167,Thailand,3297,58,3111,128,6,0,2,1.76,94.36,1.86,3250,47,1.45,South-East Asia,94.358508,1.759175,3.882317
172,Turkey,227019,5630,210469,10920,919,17,982,2.48,92.71,2.67,220572,6447,2.92,Europe,92.709861,2.479969,4.810170